name: karnama
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_animate: ^4.5.2
  lottie: ^3.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  flutter_launcher_icons: ^0.14.3
  mockito: ^5.4.4
  provider: ^6.1.2
  flutter_bloc: ^9.0.0
  sqflite: ^2.4.1
  persian_datetime_picker:
    path: persian-datetime-picker
  shamsi_date: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  google_fonts: ^6.2.1

  
flutter:
  fonts:
    - family: iranYekan
      fonts:
        - asset: assets/fonts/iranYekan/IRANYekanMobileBlack.ttf
          weight: 900
        - asset: assets/fonts/iranYekan/IRANYekanMobileBold.ttf
          weight: 700
        # - asset: assets/fonts/iranYekan/IRANYekanMobileExtraBlack.ttf
        #   weight: 950
        - asset: assets/fonts/iranYekan/IRANYekanMobileExtraBold.ttf
          weight: 800
        - asset: assets/fonts/iranYekan/IRANYekanMobileLight.ttf
          weight: 300
        - asset: assets/fonts/iranYekan/IRANYekanMobileMedium.ttf
          weight: 500
        - asset: assets/fonts/iranYekan/IRANYekanMobileRegular.ttf
          weight: 400
        - asset: assets/fonts/iranYekan/IRANYekanMobileThin.ttf
          weight: 100
  assets:
    - assets/fonts/
    - assets/animation/splash/animation.json
    - assets/animation/home/defult.json
    - assets/img/splash/splash.png
    - assets/img/icon/icon.png



  uses-material-design: true
  generate: true # Add this line
  # localizations:
  #   delegates:
  #     - AppLocalizations.delegate
  #   supportedLocales:
  #     - en
  #     - fa

flutter_native_splash:
  color: "#ffffff" # رنگ پس‌زمینه صفحه اسپلش
  image: assets/img/splash/splash.png # مسیر تصویر لوگو
  android: true # فعال کردن اسپلش برای اندروید
  ios: true # فعال کردن اسپلش برای iOS
  android_12:
    icon_background_color: "#ffffff" # رنگ پس‌زمینه لوگو در اندروید 12
    image: assets/img/splash/splash.png # مسیر تصویر لوگو در اندروید 12

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon/icon.png" # مسیر آیکون